name: flutter_monorepo

packages:
  - .
  - packages/**

scripts:
  get:
    run: flutter pub get
    description: Run pub get for all packages

  analyze:
    run: flutter analyze .
    description: Analyze all packages

  test:
    run: flutter test
    description: Run tests
